import type {  Metadata } from "next";
import "@/styles/index.css";
import HeaderComponent from '../components/header';

export const metadata: Metadata = {
	title: "Faktury",
	description: "Generated by create next app",
	icons: "static/next.svg",
};

const RootLayout = ({Component, pageProps}:{Component:any, pageProps:any}) => {

	return (
		<>
			<header className='overflow-hidden w-full h-20 fixed top-0 left-0'>
				<HeaderComponent />
			</header>
			<main className='w-svh h-svh flex-center'>
				<div className='pt-20 w-full h-full flex-center'>
					<Component {...pageProps} />
				</div>
			</main>
		</>
	);
}
export default RootLayout;



